config/routes.rb
Rails.application.routes.draw do

  resources :schedules do
    collection do
      get :get_employee
      get :autocomplete_employee_name
      post :import
    end
    member do
      get :detail
    end
  end

  resources :performances do
    collection { post :import }
  end

resources :photos do
    collection do
      get :autocomplete_organization
      get :autocomplete_photo_activity_name
      get :photo_new
      get :search
      
      get :photo_new
      post :photo_create
      delete :photo_destroy
      get :photo_edit
      patch :photo_update
      put :photo_update
    end
      member do
      put :comment
    end
  end

  resources :holidays do
  collection { post :import }
end

  resources :leave_requests do
  collection { post :import }
end

  resources :overtime_requests do
  collection { post :import }
end

  resources :attendance_settings

  resources :employee_surveys

  resources :admin_surveys

  resources :dashboards do
    collection do
      get :company_new
      get :visi
      get :misi
      get :code_of_conduct
      get :culture
      get :value_company
    end
  end

  get 'components/index'

   get 'user_managements/index'

  get 'categories/index'

  get 'shifts/index'

  get 'blast_messages/index'

  get 'holidays/index'

  get 'values/index'

  get 'cultures/index'

  get 'visions/index'

  get 'misions/index'

  get 'code_of_conducts/index'

  get 'approvals/index'

  get 'approval_employees/index'

  get 'divisions/index'

  post '/tinymce_assets' => 'tinymce_assets#create'

  namespace :admin do
    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    get "dashboard" => "dashboard#index", :as => "dashboard"
    get "confirmation/:id" => "confirmations#index", :as => "confirmation"
    resources :sessions, only: [:destroy, :create, :new]
    resources :passwords, only: [:create, :update, :edit, :new]
    resources :companies do
      member do
        get :resend
      end
      collection do
        get :get_city
        post :search
        get :search
      end
    end
    resources :blast_messages, only: [:index, :create] do
      collection do
        get :autocomplete_company_email
      end
    end
    root :to => "sessions#new"
  end

  resources :user_managements

  devise_for :users
  resources :users
  

  resources :organizations do
    member do
      get :position_edit
    end
    collection do
      get :search
      get :posisision_data
      get :position_index
      post :position_index
      get :position_show
      get :position_new
      post :position_create
      delete :position_destroy
      patch :position_update
      put :position_update
      
    end
  end

   resources :positions

  resources :fingerprints do
    collection do
      get :search
    end
  end
  
  

  resources :companies do
    collection do
      get :get_city
    end
  end

  resources :roles

  resources :approvals

  resources :asset_assignments do
    collection do
      post :return
    end
  end

  resources :recruitments do
    member do
      get :detail
      post :add_employee
    end
  end

  resources :visions, only: [:index, :show] do
    collection do
      post :setup
      get :visi_misi
    end
  end

  resources :misions, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :cultures, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :code_of_conducts, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :values, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :holidays

  resources :personal_datas

  resources :holiday_types do
    collection do
      put :update_holiday_type
      get :search
    end
  end

  resources :shifts

  resources :knowledges do
    collection do
      get :autocomplete_name
      get :autocomplete_tag_name
      get :knowledge_new
      get :search
      get :knowledge_show
      get :knowledge_new
      post :knowledge_create
      post :give_rate
      delete :knowledge_destroy
      get :knowledge_edit
      patch :knowledge_update
      put :knowledge_update
    end
    member do
      put :comment
    end
  end

  resources :blast_messages do
    collection do
      get :autocomplete_organization_name
      get :autocomplete_employee_name
    end
  end  
   
  resources :components do
  collection do
      put :update_component
      post :import
    end
  end

  resources :categories do
  collection do
      put :update_category
      post :import
    end
  end

  resources :photo_activities do
  collection do
      put :update_photo_activity
      post :import
    end
  end
  
  resources :selecteds

  resources :knowledges

  resources :knowledge_details

  resources :families do
    collection do
      put :update_family
    end
  end

  resources :employee_histories do
    collection do
      put :update_employee_histories
      post :import
    end
  end

  resources :employee_resigns

  resources :employee_working_datas do
    collection do
      put :update_employee_working_data
      post :import
    end
  end

  resources :salaries do
    collection do
      put :update_salary
      post :import
    end
  end

  resources :performances do
    collection do
      put :update_performance
    end
  end

      

  resources :components

  resources :families do
    collection do
      put :update_family
    end
  end

  resources :position_details do
    collection do
      put :update_position_detail
      post :import
    end
  end

  resources :contracts do
    collection do
      put :update_contract
      post :import
    end
  end

  resources :training_histories do
    collection do
      put :update_training_history
      post :import
    end
  end

  resources :language_skills do
    collection do
      put :update_language_skill
      post :import
    end
  end

  resources :skills do
    collection do
      put :update_skill
      post :import
    end
  end

resources :violation_details do
    collection do
      put :update_violation_detail
      post :import
    end
  end

  resources :salaries do
    collection do
      put :update_salary
    end
  end

  resources :education_details do
    collection do
      put :update_education_detail
      post :import
    end
  end

  resources :external_work_experiences do
    collection do
      put :update_external_work_experience
      post :import
    end
  end

  resources :internal_work_experiences do
    collection do
      put :update_internal_work_experience
      post :import
    end
  end

  resources :history_of_organizations do
    collection do
      put :update_history_of_organization
      post :import
    end
  end

  resources :certifications do
    collection do
      put :update_certification
      post :import
    end
  end

  resources :performances do
    collection do
      put :update_performance
    end
  end

  resources :goal_values do
    collection do
      put :update_goal_value
      get :search
      get :autocomplete_goal_value
      post :import
    end
  end

    resources :goals do
    collection do
      put :update_goal
      get :search
      get :autocomplete_goal
      post :import
    end
  end

  resources :employees do
    collection do
      get :employee_working_datas
      get :new_employee_working_datas
      post :create_employee_working_datas
      get :employee_histories
      get :new_employee_histories
      post :create_employee_histories
      get :family_details
      get :new_family_details
      post :create_family_details
      get :new_personal_data
      post :create_personal_data
      get :account_setting
      patch :change_setting
      get :absence
      get :search_absence
    end
  end
  
  resources :divisions

  resources :absences do
    collection do
      post :check_in
      post :check_out
      post :permition
      get :search_employee
    end
  end

  resources :appraisals do
    collection do
      get :get_value
      get :goal
      get :value
      get :autocomplete_goal
      get :autocomplete_goal_value
    end
  end

  resources :leave_requests

  resources :overtime_requests
   
  resources :overtime_requests do
    collection do
      put :update_overtime_request
      post :import
    end
  end

  resources :interview_results do
    member do
      patch :update_status
      put :update_status
    end
  end

  resources :test_results do
    member do
      patch :update_status
      put :update_status
      patch :set_score
      put :set_score
    end
  end

  resources :approval_levels do
    collection do 
      get :autocomplete_employee_name
    end
  end

  resources :approval_employees 
  resources :code_of_conducts, only: [:index] do
    collection do
      post :index
      post :setup
    end
  end
  resources :media_socials

  root 'dashboards#index'
  

resources :surveys do
    collection do
      post :filter
      get :filter

      post :get_view
      get :reload
      post :reorder
      get :question_list
      get "preview/:id" => "surveys#preview", as: :preview
      get :add_row
      get :remove_row
      get :question_detail
      get :question_page
      get :reset_session
      
      post :set_question
      get :edit_question
      get :add_question
      get "manage_question/:section" => "surveys#manage_question", as: :manage_question
      post "manage_question/:section" => "surveys#manage_question", as: :manage_question_post
      
      post :set_logical
      get :edit_logical
      get :add_logical
      get "manage_logical/:section" => "surveys#manage_logical", as: :manage_logical
      post "manage_logical/:section" => "surveys#manage_logical", as: :manage_logical_post
      
      post :set_page
      get :edit_page
      get :add_page
      get "manage_page/:section" => "surveys#manage_page", as: :manage_page

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :user
  has_many :survey_pages
  has_many :survey_responses
  has_many :survey_questions

  validates :name, presence: true, uniqueness: true

  self.per_page = 5
  
  def self.set_per_page(number)
    self.per_page = number
  end

end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_list.html.erb
<% surveys.each{|survey| %>
  <tr>
    <td><%= survey.name %></td>
    <td><%= survey.description %></td>
    <td><%= survey.period_start %></td>
    <td><%= survey.period_end %></td>
    <td nowrap="nowrap">
      <%= link_to raw('<i class="icon-pencil icon-white"></i>'), edit_survey_path(survey), class: 'btn btn-warning', 'data-no-turbolink' => true %>
      <%= link_to raw('<i class="icon-trash icon-white"></i>'), survey_path(survey), method: 'DELETE', 'data-confirm' => 'Are you sure you wish to delete this survey?',
        class: 'btn delete-survey btn-danger' %>
    </td>
  </tr>
<% } %>

app/views/surveys/_surveys.html.erb
<table class="table table-striped table-hover table-bordered" id="surveys">
  <thead>
    <tr>
      <th>Survey name</th>
      <th>Start</th>
      <th>End</th>
      <th>Question total</th>
      <th>Page total</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% if surveys.count > 0 %>
      <% surveys.each do |survey| %>
        <tr id="survey_<%= survey.id %>">
          <td><%= link_to survey.name, survey, :target => "_blank" %></td>
          <td><%= survey.period_start.strftime("%d %B %Y") %></td>
          <td><%= survey.period_end.strftime("%d %B %Y") %></td>
          <td><%= survey.survey_questions.count %></td>
          <td><%= survey.survey_pages.count %></td>
          <td><%= survey.status.capitalize if survey.status.present? %></td>
          <td></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="7" align="center">No survey data found!</td>
      </tr>
    <% end %>
  </tbody>
</table>
        
<div class="row" id="surveys_footer">
  <div class="col-lg-6">
    <% base = (params[:page].present? ? params[:page].to_i-1 : 0)*surveys.per_page %>
    <div class="dataTables_info" id="surveys_info">
      <% if @surveys_count > 0 %>
        Showing <%= base+1 %> to <%= base+surveys.per_page %> of <%= @surveys_count %> entries
      <% end %>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="dataTables_paginate paging_bootstrap pagination">
      <%= pagination_links(surveys, :params => {:controller => controller_name, :action => action_name, :survey => {:name => (params[:survey][:name] if params[:user].present?), :period_start => (params[:survey][:period_start] if params[:user].present?), :period_end => (params[:survey][:period_end] if params[:user].present?), :status => (params[:survey][:status] if params[:user].present?)}}) %>
    </div>
  </div>
</div>

app/views/surveys/add_page.js.erb
<% params[:cancel] ||= false %>
<% unless params[:cancel] %>
	$("#set-page-form").html("<%= j(render '/wizards/set_page') %>")
	$("#close-page-link").removeClass("hide")
	set_hide_button()
	$('html, body').animate({
    scrollTop: $("#set-page-form").offset().top
	}, 2000);
<% else %>
	$("#set-page-form").html("")
	$("#close-page-link").addClass("hide")
<% end %>

app/views/surveys/add_question.js.erb
<% params[:cancel] ||= false %>
<% unless params[:cancel] %>
	$("#set-question-form").html("<%= j(render '/wizards/set_question') %>")
	$("#close-question-link").removeClass("hide")
	$('html, body').animate({
    scrollTop: $("#set-question-form").offset().top
	}, 2000);
<% else %>
	$("#set-question-form").html("")
	$("#close-question-link").addClass("hide")
<% end %>

app/views/surveys/add_row.js.erb
<% if params[:section] == "radio_button_other" || params[:section] == "checkbox_other" %>
	$("<%= j(render '/values/'+params[:section], index: (params[:index].to_i + 1), id: params[:id], current_value: session[current_user.id.to_s]['question'][params[:id]]) %>").insertBefore($("#extra_panel"))
	$("#<%= params[:section] %>_button_0").hide()

<% else %>
	<%# textbox_text, radio_button %>
	$("<%= j(render '/values/'+params[:section]+'_item', index: (params[:index].to_i + 1), id: params[:id], current_value: session[current_user.id.to_s]['question'][params[:id]]) %>").insertAfter($("#<%= params[:section] %>_group_<%= params[:index] %>"))
	total_button = $(".<%= params[:section] %>_button").length
	$(".<%= params[:section] %>_button").hide()
	$($(".<%= params[:section] %>_button")[total_button-1]).show()
<% end %>

<% if params[:section] == "radio_button" || params[:section] == "checkbox" %>
	if($(".<%= params[:section] %>_button").length == 1){
		$($("#<%= params[:section] %>_other_button_0").children("span")[0]).show()
	} else {
		$($("#<%= params[:section] %>_other_button_0").children("span")[0]).hide()
	}
<% end %>

app/views/surveys/dumb.html.erb
<div class='panel box'>
	<header class='panel-heading'>
		<span class='tools'>
			<a onclick='editPriview();' class='fa fa-pencil'></a>
			<a onclick='copyPreview()' class='fa fa-copy'></a>
			<a onclick='deletePreview();' class='fa fa-trash-o'></a>
		</span>
	</header>
	<div class='panel-body'>
		<div class='form-group'>   
			<div class='col-lg-12 checkbox'>
				<input type='checkbox' checked='' >
				<label>Data Validation</label>
			</div>
		</div>
		<div class='form-group'>   
			<div class='col-lg-2'>
				<select class='form-control' id='question' name='question'>
					<option value='Select At Least'>Select At Least</option>
					<option value='Select At Most'>Select At Most</option>
					<option value='Select Exactly'>Select Exactly</option>
				</select>
			</div>
			<div class='col-lg-2'>
				<input type='text' class='form-control' placeholder=''>
			</div>
			<div class='col-lg-8'>
				<input type='text' class='form-control' placeholder=''>
			</div>
		</div>
	</div>
</div>

<div class='panel box'><header class='panel-heading'><span class='tools'><a onclick='editPriview();' class='fa fa-pencil'></a><a onclick='copyPreview()' class='fa fa-copy'></a><a onclick='deletePreview();' class='fa fa-trash-o'></a></span></header><div class='panel-body'></div>







<table class='table table-striped table-hover table-bordered' id='editable-sample'><thead><tr><th></th><% params[:question][:nilai][:column].each do |x| %><th><%= x %></th><% end %></tr></thead><tbody><% params[:question][:nilai][:row].each do |x| %><tr><td><%= x %></td><% [:question][:nilai][:column].each do |y| %><td><input type='checkbox'></td><% end %></tr><% end %></tbody></table>


## ranking
<div class='form-group'>
    <label class='col-lg-2 control-label'>Option</label>
    <div class='col-lg-6'>
        <textarea class='form-control'></textarea>
    </div>
    <label class='col-lg-2 control-label'>Use 'Enter' for seperate item</label> 
</div>

<div class='form-group'>
    <label class='col-lg-2 control-label'>Answer field</label>
    <div class='col-lg-6'>
        <input class='form-control'></input>
    </div>
    <label class='col-lg-2 control-label'>if blank, first option will be default</label> 
</div>

<div class='form-group'>
    <label class='col-lg-2 control-label'>Ranking</label>
    <div class='col-lg-8'>
        <input class='form-control' type='number'>to<input class='form-control' type='number'></input>
    </div>
</div>



## percentage
<div class='form-group'>
    <div class='col-lg-2'></div>
    <div class='col-lg-3'>
        <input class='form-control' placeholder='Text Before'></input>
    </div>
    <div class='col-lg-3'>
        <input class='form-control' placeholder='Text After'></input>
    </div>
</div>

<div class='form-group'>
    <label class='col-lg-2 control-label'>Answer field</label>
    <div class='col-lg-3'>
        <input class='form-control'></input>
    </div>
    <label class='col-lg-2 control-label'>0-100</label> 
</div>

<div class='form-group'>
    <label class='col-lg-2 control-label'>Increment</label>
    <div class='col-lg-3'>
        <input class='form-control'></input>
    </div>
    <label class='col-lg-2 control-label'>Only allow even number, max 100</label> 
</div>


## radio scale
<div class='form-group'>
    <div class='col-lg-2'></div>
    <div class='col-lg-3'>
        <input class='form-control' placeholder='Text Before'></input>
    </div>
    <div class='col-lg-3'>
        <input class='form-control' placeholder='Text After'></input>
    </div>
</div>

<div class='form-group'>
    <label class='col-lg-2 control-label'>Answer field</label>
    <div class='col-lg-3'>
        <input class='form-control'></input>
    </div>
    <label class='col-lg-2 control-label'>0-100</label> 
</div>

<div class='form-group'>
    <label class='col-lg-2 control-label'>Increment</label>
    <div class='col-lg-3'>
        <input class='form-control'></input>
    </div>
    <label class='col-lg-2 control-label'>Only allow even number, max 100</label> 
</div>


<div id='row_origin'><div class='form-group'><div class='col-lg-4'><input class='form-control' placeholder='Text Before'></input></div><div class='col-lg-4'> <input type='text' placeholder='Text After' class='form-control'> <span class='input-group-btn add-on'> <button class='btn btn-primary' type='button' onclick='tambahRowScale(0);'><i class='fa fa-plus'></i></button> </span></div> </div> </div> <div id='tambah_row'></div>

<div class='form-group'><label class='col-lg-2 control-label'>Increment</label><div class='col-lg-4'><input type='text' id='help' class='form-control' placeholder=''></div><label class='col-lg-2 control-label'>Max 100</label></div>

app/views/surveys/edit_logical.js.erb
<% params[:cancel] ||= false %>
<% unless params[:cancel] %>
	$("#set-logical-form").html("<%= j(render '/wizards/set_logical', id: params[:id]) %>")
	set_hide_button()
	$('html, body').animate({
    scrollTop: $("#set-logical-form").offset().top
	}, 2000);
<% else %>
	$("#set-logical-form").html("")
<% end %>

app/views/surveys/edit_page.js.erb
<% params[:cancel] ||= false %>
<% params[:is_background] = params[:is_background].present? ? params[:is_background].to_s : 'false' %>
<% unless params[:cancel] %>
	$("#set-<%= params[:is_background]=='true' ? 'background' : 'page' %>-form").html("<%= j(render '/wizards/set_page', id: params[:id], is_background: params[:is_background]) %>")
	set_hide_button()
	$('html, body').animate({
    scrollTop: $("#set-<%= params[:is_background]=='true' ? 'background' : 'page' %>-form").offset().top
	}, 2000);
<% else %>
	$("#set-<%= params[:is_background]=='true' ? 'background' : 'page' %>-form").html("")
<% end %>
$('.colorpicker-default').colorpicker({
  format: 'hex'
});

app/views/surveys/index.html.erb
<div class="col-sm-12">
  <section class="panel">
    <header class="panel-heading">
      List Surveys
    </header>
    <div class="panel-body">
      <div class="adv-table editable-table ">
        <div class="clearfix form-group">
          <div class="btn-group">
            <%= link_to new_survey_path, id: "editable-sample_new", class: "btn btn-primary" do %>
              Add New <i class="fa fa-plus"></i>
            <% end %>
          </div>
          <div class="btn-group pull-right">
            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
            </button>
            <ul class="dropdown-menu pull-right">
              <li><a href="#" onclick="javascript:print();">Print</a></li>
              <!-- <li><%#= link_to "Export to CSV", surveys_path(format: "csv") %></li>
              <li><%#= link_to "Export to Excel", surveys_path(format: "xls") %></li> -->
            </ul>
          </div>
        </div>
        <div class="space15"></div>

        <div class="clearfix">
          <%= form_for(@survey, url: filter_surveys_path, html: {class: "form-horizontal form-response", role: "form", method: :post}, remote: true) do |f| %>
            <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
              
            <div class="form-group">
              <%= f.label :name, "Survey Name", class: "col-lg-2 control-label" %>
              <div class="col-lg-3">
                <%= f.text_field :name, class: "form-control", placeholder: "Survey name" %>
              </div>

              <%= f.label :period_start, "Periode", class: "col-lg-2 col-lg-offset-1 control-label" %>
              <div class="col-lg-4">
                <div class="input-group input-large" data-date="13/07/2013" data-date-format="mm/dd/yyyy">
                  <%= f.text_field :period_start, class: "form-control dpd1", placeholder: "Start" %>
                  <span class="input-group-addon">To</span>
                  <%= f.text_field :period_end, class: "form-control dpd2", placeholder: "End" %>
                </div>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :status, class: "col-lg-2 control-label" %>
              <div class="col-lg-3">
                <%= f.select :status, options_for_select([['All', 'all'], ['Open', 'open'], ['Closed', 'closed']], f.object.status), {}, placeholder: "Status", class: "form-control" %>
              </div>
              <div class="col-lg-6 col-lg-offset-1">
                <%= f.button "Search", class: "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="space15"></div>

        <%= render 'surveys', :surveys => @surveys %>

      </div>
    </div>
  </section>
</div>

app/views/surveys/index.js.erb
$("#surveys_footer").remove()
$("#surveys").replaceWith("<%= j(render 'surveys', :surveys => @surveys) %>")

app/views/surveys/manage_logical.js.erb
<% if params[:section] == "remove" %>
	<% unless @error.present? %>
		$("#logical-preview-<%= params[:id].to_s %>").remove()
	<% end %>

<% elsif params[:section] == "update" %>
	<% unless @error.present? %>
		$("#set-logical-form").html("")
		$("#logical-preview-<%= params[:id].to_s %>").replaceWith("<%= j(render '/questions/logical', logical: params[:logical], id: params[:logical][:target], disabled: true) %>")
	<% end %>

<% end %>

app/views/surveys/manage_page.js.erb
<% params[:is_background] = params[:is_background].present? ? params[:is_background].to_s : 'false' %>
<% if params[:section] == "remove" %>
	<% unless @error.present? %>
		$("#<%= params[:is_background]=='true' ? 'background' : 'page' %>-preview-<%= params[:id].to_s %>").remove()
	<% end %>

<% elsif params[:section] == "update" %>
	<% unless @error.present? %>
		$("#set-<%= params[:is_background]=='true' ? 'background' : 'page' %>-form").html("")
		$("#<%= params[:is_background]=='true' ? 'background' : 'page' %>-preview-<%= params[:id].to_s %>").replaceWith("<%= j(render '/questions/page', page: params[:pages], id: params[:pages][:id], is_background: params[:is_background]) %>")
	<% end %>

<% end %>

app/views/surveys/manage_question.js.erb
<% if params[:section] == "remove" %>
	<% unless @error.present? %>
		$("#question-preview-<%= params[:id].to_s %>").remove()
	<% end %>
	
<% elsif params[:section] == "duplicate" %>
	<% unless @error.present? %>
		$("#question-preview").append("<%= j(render '/questions/index', question: session[current_user.id.to_s]['question'][@current_id], id: @current_id, disabled: true) %>")
	<% end %>

<% elsif params[:section] == "update" %>
	<% unless @error.present? %>
		$("#set-question-form").html("")
		$("#question-preview-<%= params[:id].to_s %>").replaceWith("<%= j(render '/questions/index', question: params[:question], id: params[:question][:id], disabled: true) %>")
	<% end %>

<% end %>

app/views/surveys/preview.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="ThemeBucket">
    <link rel="shortcut icon" href="/assets/favicon.png">

    <title>eSurvey</title>

    <!--Core CSS -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <script data-turbolinks-track="true" src="/assets/jquery.js?body=1"></script>
    
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]>
    <script src="js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <% current_page = session["#{current_user.id.to_s}"]['pages'][params[:id].to_i] %>
  <% questions = session["#{current_user.id.to_s}"]['question'] %>
  <% background = current_page['background'].gsub("public/","/") if current_page.present? && current_page['background'].present? %>
  <% set_background = (current_page['color'].present? ? "background: #{current_page['color']};" : "background: url('#{background}') no-repeat; background-size: 100%;") %>
  <body style="<%= set_background %>">

    <% if current_page.present? %>
      <div class="container current-page">
        <%= render "/questions/page", page: current_page, id: params[:id], is_background: true, exclude_action: true %>
      </div>
      
      <div class="container">
        <% if current_page['questions'].present? %>
          <% current_page['questions'].each do |id| %>
            <% question = questions[id.to_i] %>
            <%= render "/questions/index", question: question, id: id, disabled: true, exclude_action: true if question.present? %>
          <% end %>
        <% end %>

        <div class="form-group">
          <%= (link_to "Previous", preview_surveys_path((params[:id].to_i-1)), class: "btn btn-primary pull-left") if session["#{current_user.id.to_s}"]['pages'][(params[:id].to_i - 1)].present? %>
        </div>

        <div class="form-group">
          <%= (link_to "Next", preview_surveys_path((params[:id].to_i+1)), class: "btn btn-primary pull-right") if session["#{current_user.id.to_s}"]['pages'][(params[:id].to_i + 1)].present? %>
        </div>
    	</div>
    <% else %>
    	<p>No Content Here</p>
    <% end %>

   <!-- Placed js at the end of the document so the pages load faster -->

   <!--Core js-->
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>