config/routes.rb
Rails.application.routes.draw do

  resources :schedules do
    collection do
      get :get_employee
      get :autocomplete_employee_name
      post :import
    end
    member do
      get :detail
    end
  end

  resources :performances do
    collection { post :import }
  end

resources :photos do
    collection do
      get :autocomplete_organization
      get :autocomplete_photo_activity_name
      get :photo_new
      get :search
      
      get :photo_new
      post :photo_create
      delete :photo_destroy
      get :photo_edit
      patch :photo_update
      put :photo_update
    end
      member do
      put :comment
    end
  end

  resources :holidays do
  collection { post :import }
end

  resources :leave_requests do
  collection { post :import }
end

  resources :overtime_requests do
  collection { post :import }
end

  resources :attendance_settings

  resources :employee_surveys

  resources :admin_surveys

  resources :dashboards do
    collection do
      get :company_new
      get :visi
      get :misi
      get :code_of_conduct
      get :culture
      get :value_company
    end
  end

  get 'components/index'

   get 'user_managements/index'

  get 'categories/index'

  get 'shifts/index'

  get 'blast_messages/index'

  get 'holidays/index'

  get 'values/index'

  get 'cultures/index'

  get 'visions/index'

  get 'misions/index'

  get 'code_of_conducts/index'

  get 'approvals/index'

  get 'approval_employees/index'

  get 'divisions/index'

  post '/tinymce_assets' => 'tinymce_assets#create'

  namespace :admin do
    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    get "dashboard" => "dashboard#index", :as => "dashboard"
    get "confirmation/:id" => "confirmations#index", :as => "confirmation"
    resources :sessions, only: [:destroy, :create, :new]
    resources :passwords, only: [:create, :update, :edit, :new]
    resources :companies do
      member do
        get :resend
      end
      collection do
        get :get_city
        post :search
        get :search
      end
    end
    resources :blast_messages, only: [:index, :create] do
      collection do
        get :autocomplete_company_email
      end
    end
    root :to => "sessions#new"
  end

  resources :user_managements

  devise_for :users
  resources :users
  

  resources :organizations do
    member do
      get :position_edit
    end
    collection do
      get :search
      get :posisision_data
      get :position_index
      post :position_index
      get :position_show
      get :position_new
      post :position_create
      delete :position_destroy
      patch :position_update
      put :position_update
      
    end
  end

   resources :positions

  resources :fingerprints do
    collection do
      get :search
    end
  end
  
  

  resources :companies do
    collection do
      get :get_city
    end
  end

  resources :roles

  resources :approvals

  resources :asset_assignments do
    collection do
      post :return
    end
  end

  resources :recruitments do
    member do
      get :detail
      post :add_employee
    end
  end

  resources :visions, only: [:index, :show] do
    collection do
      post :setup
      get :visi_misi
    end
  end

  resources :misions, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :cultures, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :code_of_conducts, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :values, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :holidays

  resources :personal_datas

  resources :holiday_types do
    collection do
      put :update_holiday_type
      get :search
    end
  end

  resources :shifts

  resources :knowledges do
    collection do
      get :autocomplete_name
      get :autocomplete_tag_name
      get :knowledge_new
      get :search
      get :knowledge_show
      get :knowledge_new
      post :knowledge_create
      post :give_rate
      delete :knowledge_destroy
      get :knowledge_edit
      patch :knowledge_update
      put :knowledge_update
    end
    member do
      put :comment
    end
  end

  resources :blast_messages do
    collection do
      get :autocomplete_organization_name
      get :autocomplete_employee_name
    end
  end  
   
  resources :components do
  collection do
      put :update_component
      post :import
    end
  end

  resources :categories do
  collection do
      put :update_category
      post :import
    end
  end

  resources :photo_activities do
  collection do
      put :update_photo_activity
      post :import
    end
  end
  
  resources :selecteds

  resources :knowledges

  resources :knowledge_details

  resources :families do
    collection do
      put :update_family
    end
  end

  resources :employee_histories do
    collection do
      put :update_employee_histories
      post :import
    end
  end

  resources :employee_resigns

  resources :employee_working_datas do
    collection do
      put :update_employee_working_data
      post :import
    end
  end

  resources :salaries do
    collection do
      put :update_salary
      post :import
    end
  end

  resources :performances do
    collection do
      put :update_performance
    end
  end

      

  resources :components

  resources :families do
    collection do
      put :update_family
    end
  end

  resources :position_details do
    collection do
      put :update_position_detail
      post :import
    end
  end

  resources :contracts do
    collection do
      put :update_contract
      post :import
    end
  end

  resources :training_histories do
    collection do
      put :update_training_history
      post :import
    end
  end

  resources :language_skills do
    collection do
      put :update_language_skill
      post :import
    end
  end

  resources :skills do
    collection do
      put :update_skill
      post :import
    end
  end

resources :violation_details do
    collection do
      put :update_violation_detail
      post :import
    end
  end

  resources :salaries do
    collection do
      put :update_salary
    end
  end

  resources :education_details do
    collection do
      put :update_education_detail
      post :import
    end
  end

  resources :external_work_experiences do
    collection do
      put :update_external_work_experience
      post :import
    end
  end

  resources :internal_work_experiences do
    collection do
      put :update_internal_work_experience
      post :import
    end
  end

  resources :history_of_organizations do
    collection do
      put :update_history_of_organization
      post :import
    end
  end

  resources :certifications do
    collection do
      put :update_certification
      post :import
    end
  end

  resources :performances do
    collection do
      put :update_performance
    end
  end

  resources :goal_values do
    collection do
      put :update_goal_value
      get :search
      get :autocomplete_goal_value
      post :import
    end
  end

    resources :goals do
    collection do
      put :update_goal
      get :search
      get :autocomplete_goal
      post :import
    end
  end

  resources :employees do
    collection do
      get :employee_working_datas
      get :new_employee_working_datas
      post :create_employee_working_datas
      get :employee_histories
      get :new_employee_histories
      post :create_employee_histories
      get :family_details
      get :new_family_details
      post :create_family_details
      get :new_personal_data
      post :create_personal_data
      get :account_setting
      patch :change_setting
      get :absence
      get :search_absence
    end
  end
  
  resources :divisions

  resources :absences do
    collection do
      post :check_in
      post :check_out
      post :permition
      get :search_employee
    end
  end

  resources :appraisals do
    collection do
      get :get_value
      get :goal
      get :value
      get :autocomplete_goal
      get :autocomplete_goal_value
    end
  end

  resources :leave_requests

  resources :overtime_requests
   
  resources :overtime_requests do
    collection do
      put :update_overtime_request
      post :import
    end
  end

  resources :interview_results do
    member do
      patch :update_status
      put :update_status
    end
  end

  resources :test_results do
    member do
      patch :update_status
      put :update_status
      patch :set_score
      put :set_score
    end
  end

  resources :approval_levels do
    collection do 
      get :autocomplete_employee_name
    end
  end

  resources :approval_employees 
  resources :code_of_conducts, only: [:index] do
    collection do
      post :index
      post :setup
    end
  end
  resources :media_socials

  root 'dashboards#index'
  

resources :surveys do
    collection do
      post :filter
      get :filter

      post :get_view
      get :reload
      post :reorder
      get :question_list
      get "preview/:id" => "surveys#preview", as: :preview
      get :add_row
      get :remove_row
      get :question_detail
      get :question_page
      get :reset_session
      
      post :set_question
      get :edit_question
      get :add_question
      get "manage_question/:section" => "surveys#manage_question", as: :manage_question
      post "manage_question/:section" => "surveys#manage_question", as: :manage_question_post
      
      post :set_logical
      get :edit_logical
      get :add_logical
      get "manage_logical/:section" => "surveys#manage_logical", as: :manage_logical
      post "manage_logical/:section" => "surveys#manage_logical", as: :manage_logical_post
      
      post :set_page
      get :edit_page
      get :add_page
      get "manage_page/:section" => "surveys#manage_page", as: :manage_page

app/models/education_detail.rb
class EducationDetail < ActiveRecord::Base
	belongs_to :employee

def self.to_csv(params, options = {})
  CSV.generate(options) do |csv|
    csv << ["employee_name", "grade", "institution", "start", "end", "major", "final_score"]
    where(:employee_id => params[:id]).each do |education_detail|
      csv << [education_detail.employee.name, education_detail.grade, education_detail.institution, education_detail.start, education_detail.end, education_detail.major, education_detail.final_score ]
    end
  end
end

def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      education_detail = find_by_id(row["ID"]) || new
      employee = Employee.find_by_name(row.to_hash['employee_name'])
      #raise row.to_hash.inspect
      parameters = ActionController::Parameters.new(row.to_hash.merge(employee_id: employee.id))
      education_detail.update(parameters.permit(:grade, :institution, :start, :end, :major, :final_score, :employee_id))
      education_detail.save!
    end
  end
=begin
def self.import(file)
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
    education_detail = find_by_id(row["id"]) || new
    education_detail.attributes = row.to_hash.slice(*accessible_attributes)
    education_detail.save!
  end
end
=end
def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end

end

app/controllers/education_details_controller.rb
class EducationDetailsController < ApplicationController

	def index
		
		@education_details = EducationDetail.where(:employee_id => params[:id])
		respond_to do |format|
    	format.html
    	format.csv { send_data @education_details.to_csv(params) }
    	format.xls
  	end
	end

	def import

  EducationDetail.import(params[:file])
  redirect_to employee_histories_path(:id => params[:id]), notice: "Imported Success."
	end

	def new

		@education_detail = EducationDetail.new
		@grade = ['SD', 'SMP', 'SMA', 'Sarjana', 'Magister', 'Doktor']
	  	respond_to do |format|
	    	format.js
		end
	end

		def create
		change_date_format(params)
		@education_detail = EducationDetail.new(education_detail_params)
		respond_to do |format|
	      format.js
	    end
	end

	def change_date_format(params)
    if params[:education_detail].present?
      if params[:education_detail][:start].present?
        base_date = params[:education_detail][:start].split("/")
        params[:education_detail][:start] = base_date[2] + "-" + base_date[1] + "-" + base_date[0]
  		end
  		if params[:education_detail][:end].present?
        base_date = params[:education_detail][:end].split("/")
        params[:education_detail][:end] = base_date[2] + "-" + base_date[1] + "-" + base_date[0]
  		end
  	end
  end

	def destroy
		params[:check].each do |delete|
			EducationDetail.find_by_id(delete).destroy
		end
		respond_to do |format|
	      format.js
	    end
	end

	def edit
		@education_detail = EducationDetail.find_by_id(params[:id])
	  @grade = ['SD', 'SMP', 'SMA', 'Sarjana', 'Magister', 'Doktor']	
	  	respond_to do |format|
	    	format.js
		end
	end

	def update_education_detail
		@education_detail = EducationDetail.find_by_id(params[:education_detail][:id])
		@education_detail.update(education_detail_params)
		respond_to do |format|
	      format.js
	    end
	end

	private
		def education_detail_params
			params.require(:education_detail).permit(:grade, :institution, :start, :end, :major, :final_score, :employee_id)
		end
end

app/helpers/education_details_helper.rb
module EducationDetailsHelper
end

app/views/education_details/_data.html.erb
<%= "<tr id=\"data_#{education_detail.id}\">".html_safe if params[:action] != "update_education_detail" %>  
<td>
  <div class="checkbox check-default">
    <input id="checkbox<%= education_detail.id %>" type="checkbox" value="<%= education_detail.id %>" class="child-education_detail child-box" data-section="education_detail" data-educationdetail="child">
    <label for="checkbox<%= education_detail.id %>"></label>
  </div>
</td>
    <td><%= education_detail.grade %></td>
    <td><%= education_detail.institution %></td>
    <td><%= education_detail.start %></td>
    <td><%= education_detail.end %></td>
    <td><%= education_detail.major %></td>
    <td><%= education_detail.final_score %></td>
    <%= "</tr>".html_safe if params[:action] != "update_education_detail" %>

app/views/education_details/_form.html.erb
<%# if params[:action] == "new"%>
	<tr id="data_<%= education_detail.id %>">
<%# end %>
	<%= form_for(education_detail, html: { role: "form", multipart: true}, remote: true) do |f| %>
		<td>
			<div class="checkbox check-default">
                <input id="checkbox12" type="checkbox" value="1">
                <label for="checkbox12"></label>
            </div>
		</td>

		<td>
			<%= f.select :grade, options_for_select(grade) %>
			<% if params[:action] == "new"%>
				<%= f.hidden_field :employee_id, :value => params[:employee_id]%>
			<% else %>
				<%= f.hidden_field :id, :value => params[:id] %>
			<% end %>
		</td>

		<td>
			<%= f.text_field :institution, :class => "full-width", :placeholder => "institution" %>
		</td>

		<td>
			<div class="input-append success date">
                <%= f.text_field :start, :class => "form-control", :style => "width:75px", value: (f.object.start.present? ? f.object.start.to_date.strftime("%d/%m/%Y") : (params[:education_detail].present? ? params[:education_detail][:start] : "")) %>
                <span class="add-on"><span class="arrow"></span><i class="fa fa-th"></i></span> 
            </div>
		</td>

		<td>
			<div class="input-append success date">
                <%= f.text_field :end, :class => "form-control", :style => "width:75px", value: (f.object.end.present? ? f.object.end.to_date.strftime("%d/%m/%Y") : (params[:education_detail].present? ? params[:education_detail][:end] : "")) %>
                <span class="add-on"><span class="arrow"></span><i class="fa fa-th"></i></span> 
            </div>
		</td>

		<td>
			<%= f.text_field :major, :class => "full-width", :placeholder => "Major" %>
		</td>
		
		<td>
			<%= f.number_field :final_score, :class => "full-width", :placeholder => "" %>
		</td>

		<td>
			<p>
				<% if params[:action] == "new" %>
        	<%= f.submit "Add", class: "btn btn-success", :onclick => "submit_education_detail();"%>
        	<button class="btn btn-danger" onclick="$(this).parent().parent().parent().remove(); $('.new-rec').remove()"> Cancel </button>
      	<% else %>
      		<%= f.submit "Update", class: "btn btn-success", :onclick => "update_education_detail();"%>
        	<button class="btn btn-danger" onclick="reset_view_<%= f.object.id %>()"> cancel </button>
      	<% end %>
      </p>
      <% if f.object.id.present? %>
				<script type="text/javascript">
					function reset_view_<%= f.object.id %>() {
						$("#data_<%= f.object.id %>").replaceWith("<%= j(render 'data', :education_detail => f.object) %>");
						$('#toolbar_education_detail').addClass('hide');
						$('#button_edit_education_detail').addClass('hide');
						$('#button_remove_education_detail').addClass('hide');
						$(".child-box").each(function(){
						  $(this).click(function() {
						    section = $(this).attr("data-section")
						    children = $(".child-" + section)
						    // $(this).parent().parent().parent().toggleClass('row_selected')

						    show_button($(this))
						    
						    selected_count = 0
						    children.each(function(){ if ($(this).is(':checked')) { selected_count += 1 } })
						    if (selected_count==children.length) {
						      $(".parent-" + section).prop('checked', true)
						    } else{
						      $(".parent-" + section).prop('checked', false)
						    };
						  })
						})
					}
				</script>
			<% end %>
		</td>
	<% end %>
<%# if params[:action] == "new"%>
	</tr>
<%# end %>

app/views/education_details/index.html.erb
  <div class="grid simple">
    <div class="grid-body no-border has-tab">
      <%= render '/employees/tab_nav'%>         
      <div class="tab-content">
        <section class="tab-pane active">
          <div class="row toolbar-block">
            <h4 class="semi-bold col-md-4">
              <i class="fa fa-check-square"></i> Education Detail
            </h4>
            <div class="col-md-8">
              <div class="toolbar pull-right">
                <%= link_to "<span class=\"fa fa-plus\"></span> Add New".html_safe, new_education_detail_path(:employee_id => params[:id]), :remote => true, :class => "btn btn-success" %>
                <%= button_tag "Tools <i class=\"fa fa-angle-down\"></i>".html_safe, :class => "btn btn-default dropdown-toggle", :"data-toggle" => "dropdown" %>
                <ul class="dropdown-menu pull-right">
                  <li><%= link_to "Export to CSV", education_details_path(format: "csv", id: params[:id]) %></li>
                  <li><%= link_to "Export to Excel", education_details_path(format: "xls",id: params[:id]) %></li>
                  <li data-toggle="modal" data-target="#upload_modal"><a>Import from CSV</a></li>
                </ul>
              </div>
              <div class="toolbar pull-right hide" id="toolbar_upload">
                <div class="table-tools-actions">
                  <%= button_tag "<span class=\"fa fa-cloud-upload\"></span> Upload".html_safe, :class => "btn", :"data-toggle" => "modal", :"data-target" => "#upload_modal" %>
                  <div class="separator">&nbsp;</div>
                </div>
              </div>
              <div class="toolbar pull-right hide" id="toolbar_education_detail">
                <div class="table-tools-actions">
                  <%= button_tag "<span class=\"fa fa-edit\"></span> Edit".html_safe, :class => "btn", :onclick => "edit_education_detail()", :id => "button_edit_education_detail" %>
                  <%= button_tag "<span class=\"fa fa-trash\"></span> Remove".html_safe, :class => "btn", :"data-toggle" => "modal", :"data-target" => "#confirm_modal", :id => "button_remove_education_detail", :"data-section" => "education_detail", :onclick => "set_delete_url('/education_details/delete')" %>
                  <div class="separator">&nbsp;</div>
                </div>
              </div>
            </div>
          </div>
          <table class="table no-more-tables table-striped table-hover" id="education_detail">
            <thead>
              <tr>
                <th style="width: 45px" >
                  <div class="checkbox check-default">
                    <input id="checkall_education_detail" data-section="education_detail" data-educationdetail="parent" type="checkbox" value="1" class="checkall parent-education_detail">
                    <label for="checkall_education_detail"></label>
                  </div>
                </th>
                <th>Grade</th>
                <th>Institution</th>
                <th>start</th>
                <th>end</th>
                <th>Major</th>
                <th>Final Score</th>
              </tr>
            </thead>
            <tbody>
              <% if @education_details.count != 0 %>
                <% @education_details.each do |education_detail| %>
                  <%= render 'education_details/data', :education_detail => education_detail%>
                <% end %>
              <% else %>
                <tr>
                  <td colspan='6' align='center'>No Data Found !</td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </section>
      </div>
    </div>
    <br class="clear"/>
  </div>

app/views/education_details/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Employee name</Data></Cell>
        <Cell><Data ss:Type="String">Grade</Data></Cell>
        <Cell><Data ss:Type="String">Institution</Data></Cell>
        <Cell><Data ss:Type="String">Start</Data></Cell>
        <Cell><Data ss:Type="String">End</Data></Cell>
        <Cell><Data ss:Type="String">Major</Data></Cell>
        <Cell><Data ss:Type="String">Final Score</Data></Cell>
      </Row>
    <% @education_details.each do |education_detail| %>
      <Row>
        <Cell><Data ss:Type="String"><%= education_detail.employee.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= education_detail.grade %></Data></Cell>
        <Cell><Data ss:Type="String"><%= education_detail.institution %></Data></Cell>
        <Cell><Data ss:Type="String"><%= education_detail.start %></Data></Cell>
        <Cell><Data ss:Type="String"><%= education_detail.end %></Data></Cell>
        <Cell><Data ss:Type="String"><%= education_detail.major %></Data></Cell>
        <Cell><Data ss:Type="String"><%= education_detail.final_score %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>