config/routes.rb
Rails.application.routes.draw do

  resources :schedules do
    collection do
      get :get_employee
      get :autocomplete_employee_name
      post :import
    end
    member do
      get :detail
    end
  end

  resources :performances do
    collection { post :import }
  end

resources :photos do
    collection do
      get :autocomplete_organization
      get :autocomplete_photo_activity_name
      get :photo_new
      get :search
      
      get :photo_new
      post :photo_create
      delete :photo_destroy
      get :photo_edit
      patch :photo_update
      put :photo_update
    end
      member do
      put :comment
    end
  end

  resources :holidays do
  collection { post :import }
end

  resources :leave_requests do
  collection { post :import }
end

  resources :overtime_requests do
  collection { post :import }
end

  resources :attendance_settings

  resources :employee_surveys

  resources :admin_surveys

  resources :dashboards do
    collection do
      get :company_new
      get :visi
      get :misi
      get :code_of_conduct
      get :culture
      get :value_company
    end
  end

  get 'components/index'

   get 'user_managements/index'

  get 'categories/index'

  get 'shifts/index'

  get 'blast_messages/index'

  get 'holidays/index'

  get 'values/index'

  get 'cultures/index'

  get 'visions/index'

  get 'misions/index'

  get 'code_of_conducts/index'

  get 'approvals/index'

  get 'approval_employees/index'

  get 'divisions/index'

  post '/tinymce_assets' => 'tinymce_assets#create'

  namespace :admin do
    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    get "dashboard" => "dashboard#index", :as => "dashboard"
    get "confirmation/:id" => "confirmations#index", :as => "confirmation"
    resources :sessions, only: [:destroy, :create, :new]
    resources :passwords, only: [:create, :update, :edit, :new]
    resources :companies do
      member do
        get :resend
      end
      collection do
        get :get_city
        post :search
        get :search
      end
    end
    resources :blast_messages, only: [:index, :create] do
      collection do
        get :autocomplete_company_email
      end
    end
    root :to => "sessions#new"
  end

  resources :user_managements

  devise_for :users
  resources :users
  

  resources :organizations do
    member do
      get :position_edit
    end
    collection do
      get :search
      get :posisision_data
      get :position_index
      post :position_index
      get :position_show
      get :position_new
      post :position_create
      delete :position_destroy
      patch :position_update
      put :position_update
      
    end
  end

   resources :positions

  resources :fingerprints do
    collection do
      get :search
    end
  end
  
  

  resources :companies do
    collection do
      get :get_city
    end
  end

  resources :roles

  resources :approvals

  resources :asset_assignments do
    collection do
      post :return
    end
  end

  resources :recruitments do
    member do
      get :detail
      post :add_employee
    end
  end

  resources :visions, only: [:index, :show] do
    collection do
      post :setup
      get :visi_misi
    end
  end

  resources :misions, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :cultures, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :code_of_conducts, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :values, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :holidays

  resources :personal_datas

  resources :holiday_types do
    collection do
      put :update_holiday_type
      get :search
    end
  end

  resources :shifts

  resources :knowledges do
    collection do
      get :autocomplete_name
      get :autocomplete_tag_name
      get :knowledge_new
      get :search
      get :knowledge_show
      get :knowledge_new
      post :knowledge_create
      post :give_rate
      delete :knowledge_destroy
      get :knowledge_edit
      patch :knowledge_update
      put :knowledge_update
    end
    member do
      put :comment
    end
  end

  resources :blast_messages do
    collection do
      get :autocomplete_organization_name
      get :autocomplete_employee_name
    end
  end  
   
  resources :components do
  collection do
      put :update_component
      post :import
    end
  end

  resources :categories do
  collection do
      put :update_category
      post :import
    end
  end

  resources :photo_activities do
  collection do
      put :update_photo_activity
      post :import
    end
  end
  
  resources :selecteds

  resources :knowledges

  resources :knowledge_details

  resources :families do
    collection do
      put :update_family
    end
  end

  resources :employee_histories do
    collection do
      put :update_employee_histories
      post :import
    end
  end

  resources :employee_resigns

  resources :employee_working_datas do
    collection do
      put :update_employee_working_data
      post :import
    end
  end

  resources :salaries do
    collection do
      put :update_salary
      post :import
    end
  end

  resources :performances do
    collection do
      put :update_performance
    end
  end

      

  resources :components

  resources :families do
    collection do
      put :update_family
    end
  end

  resources :position_details do
    collection do
      put :update_position_detail
      post :import
    end
  end

  resources :contracts do
    collection do
      put :update_contract
      post :import
    end
  end

  resources :training_histories do
    collection do
      put :update_training_history
      post :import
    end
  end

  resources :language_skills do
    collection do
      put :update_language_skill
      post :import
    end
  end

  resources :skills do
    collection do
      put :update_skill
      post :import
    end
  end

resources :violation_details do
    collection do
      put :update_violation_detail
      post :import
    end
  end

  resources :salaries do
    collection do
      put :update_salary
    end
  end

  resources :education_details do
    collection do
      put :update_education_detail
      post :import
    end
  end

  resources :external_work_experiences do
    collection do
      put :update_external_work_experience
      post :import
    end
  end

  resources :internal_work_experiences do
    collection do
      put :update_internal_work_experience
      post :import
    end
  end

  resources :history_of_organizations do
    collection do
      put :update_history_of_organization
      post :import
    end
  end

  resources :certifications do
    collection do
      put :update_certification
      post :import
    end
  end

  resources :performances do
    collection do
      put :update_performance
    end
  end

  resources :goal_values do
    collection do
      put :update_goal_value
      get :search
      get :autocomplete_goal_value
      post :import
    end
  end

    resources :goals do
    collection do
      put :update_goal
      get :search
      get :autocomplete_goal
      post :import
    end
  end

  resources :employees do
    collection do
      get :employee_working_datas
      get :new_employee_working_datas
      post :create_employee_working_datas
      get :employee_histories
      get :new_employee_histories
      post :create_employee_histories
      get :family_details
      get :new_family_details
      post :create_family_details
      get :new_personal_data
      post :create_personal_data
      get :account_setting
      patch :change_setting
      get :absence
      get :search_absence
    end
  end
  
  resources :divisions

  resources :absences do
    collection do
      post :check_in
      post :check_out
      post :permition
      get :search_employee
    end
  end

  resources :appraisals do
    collection do
      get :get_value
      get :goal
      get :value
      get :autocomplete_goal
      get :autocomplete_goal_value
    end
  end

  resources :leave_requests

  resources :overtime_requests
   
  resources :overtime_requests do
    collection do
      put :update_overtime_request
      post :import
    end
  end

  resources :interview_results do
    member do
      patch :update_status
      put :update_status
    end
  end

  resources :test_results do
    member do
      patch :update_status
      put :update_status
      patch :set_score
      put :set_score
    end
  end

  resources :approval_levels do
    collection do 
      get :autocomplete_employee_name
    end
  end

  resources :approval_employees 
  resources :code_of_conducts, only: [:index] do
    collection do
      post :index
      post :setup
    end
  end
  resources :media_socials

  root 'dashboards#index'
  

resources :surveys do
    collection do
      post :filter
      get :filter

      post :get_view
      get :reload
      post :reorder
      get :question_list
      get "preview/:id" => "surveys#preview", as: :preview
      get :add_row
      get :remove_row
      get :question_detail
      get :question_page
      get :reset_session
      
      post :set_question
      get :edit_question
      get :add_question
      get "manage_question/:section" => "surveys#manage_question", as: :manage_question
      post "manage_question/:section" => "surveys#manage_question", as: :manage_question_post
      
      post :set_logical
      get :edit_logical
      get :add_logical
      get "manage_logical/:section" => "surveys#manage_logical", as: :manage_logical
      post "manage_logical/:section" => "surveys#manage_logical", as: :manage_logical_post
      
      post :set_page
      get :edit_page
      get :add_page
      get "manage_page/:section" => "surveys#manage_page", as: :manage_page

app/models/photo_activity.rb
class PhotoActivity < ActiveRecord::Base
  has_many :photo_receivers
  has_many :photo, :through => :photo_receivers
  has_many :photos

  belongs_to :user

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << ["name"]
      all.each do |photo_activity|
        csv << [photo_activity.name]
      end
    end
  end

  def self.to_csv2(options = {})
    CSV.generate(options) do |csv|
      csv << ["name"]
        all.each do |photo_activity|
      end
    end
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      photo_activity = find_by_id(row["id"]) || new
      parameters = ActionController::Parameters.new(row.to_hash)
      photo_activity.update(parameters.permit(:name))
      photo_activity.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Csv.new(file.path, nil, :ignore)
      when ".xls" then Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/photo_activities_controller.rb
class PhotoActivitiesController < ApplicationController
  def index
    @photo_activities = PhotoActivity.where("company_id=#{@current_user.company_id}").paginate(page: params[:page], per_page: 100)
    respond_to do |format|
      format.html
      format.xls
      if(params[:a] == "a")
        format.csv { send_data @photo_activities.to_csv2 }
      else
        format.csv { send_data @photo_activities.to_csv }
      end
    end
  end

  def new
    @photo_activity = PhotoActivity.new
    respond_to do |format|
      format.js
    end
  end

  def import
    PhotoActivity.import(params[:file])
    redirect_to categories_path, notice: "PhotoActivity imported."
  end

  def create
    a = @current_user.id
    b = @current_company.id
    @photo_activity = PhotoActivity.new(photo_activity_params.merge(:company_id => b, :user_id => a))
    respond_to do |format|
      format.js
    end
  end

  def destroy
    params[:check].each do |delete|
      PhotoActivity.find_by_id(delete).destroy
    end
    respond_to do |format|
      format.js
    end
  end

  def edit
    @photo_activity = PhotoActivity.find_by_id(params[:id])
    respond_to do |format|
        format.js
      end
  end

  def update
    @photo_activity = PhotoActivity.find_by_id(params[:photo_activity][:id])
    @photo_activity.update_attributes(photo_activity_params)
    respond_to do |format|
      format.js
    end
  end

  private
    def photo_activity_params
      params.require(:photo_activity).permit(:id, :name, :company_id, :user_id)
    end
end

app/helpers/photo_activities_helper.rb
module PhotoActivitiesHelper
end

app/views/photo_activities/_data.html.erb
<% if params[:action] != "update" %>
    <tr id="data_<%= photo_activity.id %>">
<% end %>
    <td>
    	<div class="checkbox check-default">
            <input id="checkbox<%= photo_activity.id %>" type="checkbox" value="<%= photo_activity.id %>" onchange="cek_checkbox();">
            <label for="checkbox<%= photo_activity.id %>"></label>
        </div>
    </td>
    <td><%= photo_activity.name %></td>
<% if params[:action] != "update" %>
    </tr>
<% end %>

app/views/photo_activities/_form.html.erb
<% if params[:action] == "new"%>
  <tr>
<% end %>
  <%= form_for(photo_activity, html: { role: "form", multipart: true}, remote: true) do |f| %>
    <td>
      <div class="checkbox check-default">
        <input id="checkbox12" type="checkbox" value="1">
        <label for="checkbox12"></label>
      </div>
    </td>
    <td>
      <%= f.text_field :name, :class => "full-width", :placeholder => "Photo Activity" %>
    </td>
    <td>
      <div>
        <% if params[:action] == "new" %>
          <%= f.submit "Add", class: "btn btn-success", :onclick => "submit_photo_activity();"%>
        <% else %>
        <%= f.hidden_field :id, :value => params[:id] %>
          <%= f.submit "Update", class: "btn btn-success", :onclick => "update_photo_activity();"%>
        <% end %>
      </div>
    </td>
  <% end %>
<% if params[:action] == "new"%>
  </tr>
<% end %>

app/views/photo_activities/_index.html.erb
<table class="table no-more-tables table-striped table-hover" id="photo_activity" >
    <thead>
        <tr><th style="width:1%" >
                <div class="checkbox check-default">
                    <input id="checkbox" type="checkbox" value="1" class="checkall">
                    <label for="checkbox"></label>
                </div>
            </th>
            <th>Photo Activity</th>
        </tr>
    </thead>
    <tbody id='dataTable' class="searchable">
        <% if @photo_activities.count > 0 %>
            <% @photo_activities.each do |photo_activity| %>
                <%= render 'data', :photo_activity => photo_activity %>
            <% end %>
        <% else %>  
            <tr>
                <td colspan="5" align="center">No photo_activity data found!</td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/photo_activities/create.js.erb
<% if @photo_activity.save %>
	$('#photo_activity tbody tr:eq(0)').remove();
	$('#button-new').show();
	$('#photo_activity tbody').prepend("<%= j(render 'data', :photo_activity => @photo_activity) %>");
<% else %>
<% end %>

app/views/photo_activities/index.html.erb
<%= javascript_tag render(:template => 'photo_activities/jsManager.js', :formats => [:js]) %>
<div class="container-fluid">
	<ul class="breadcrumb">
    <li><p>YOU ARE HERE</p></li> 
    <li><a href="#" class="active">Photo</a></li>
  </ul>
  <div class="page-title">	
   	<i class="fa fa-user"></i>
   	<h3>Photo Activities</span></h3>	
  </div>  
  <div class="grid simple">
    <div class="grid-title no-border"></div>
   	<div class="grid-body no-border">
		<div class="row toolbar-block">
     	<div class="col-md-4">
       	<div class="dataTables_filter" id="example3_filter">
         	<div class="controls">
            <div class="input-group">
              <input id="filter" type="text" class="form-control" placeholder="Search Record">
              <span class="input-group-addon ">
  	           	<i class="fa fa-search"></i>
              </span>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-8">
       	<div class="toolbar pull-right" id="toolbar_main">
         	<div class="table-tools-actions">
            <%= button_to new_photo_activity_path, :method => 'get', :class => 'btn btn-success', :remote => true do %>
    	        <span class="fa fa-plus"></span> Add New
            <% end %>
          </div>
        </div>
      <div class="toolbar pull-right" id="toolbar_main">                      
        <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
        </button>
        <ul class="dropdown-menu pull-right">
          <li><%= link_to "Export to CSV",  photo_activities_path(format: "csv") %></li>
          <li><%= link_to "Export to Excel", photo_activities_path(format: "xls") %></li>
          <li data-toggle="modal" data-target="#uploadModal"><a>Import from CSV</a></li>
        </ul>
      </div>
      <div class="toolbar pull-right" id="toolbar_def">
        <div class="table-tools-actions">
          <button class="btn" id="button_edit" onclick="edit_photo_activity()">
      	    <span class="fa fa-edit"></span> Edit
          </button> 
          <button class="btn" data-toggle="modal" data-target="#confirm_modal">
            <span class="fa fa-trash"></span> Remove
          </button> 
          <div class="separator">&nbsp;</div>
        </div>
      </div>
    </div>
  </div>
	<%= render 'index' %>
</div>
</div>
</div>

<!-- Modal Area -->

<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
  <%= render 'new' if action_name == "create" %>
  <%= render 'edit' if action_name == "update" %>
</div>

<!-- Modal Upload -->
<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Import Categories</h4>
      </div>
      <%= form_tag import_photo_activities_path, multipart: true do %>
        <div class="modal-body">
            <%= file_field_tag :file %>
        </div>
        <div class="modal-footer">
          <%= link_to "Download Template", photo_activities_path(format: "csv", :a => "a"), :class => "btn btn-success" %>
          <%= submit_tag "Import", :class => "btn btn-primary"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Modal Remove -->
<div class="modal fade" id="confirm_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <br>
          <i class="fa fa-trash-o fa-7x"></i>
          <h4 id="myModalLabel" class="semi-bold">Are you sure want to remove this item(s)</h4>
          <br>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="delete_photo_activity();">Yes</button>
        </div>
      </div>
    </div>
</div>

app/views/photo_activities/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
      </Row>
    <% @photo_activities.each do |photo_activity| %>
      <Row>
        <Cell><Data ss:Type="String"><%= photo_activity.name %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/photo_activities/new.js.erb
$('#photo_activity tbody').prepend("<%= j(render 'form', :photo_activity => @photo_activity) %>");
$('#button-new').hide();